### ISSUE TITLE
[BUG] - Player.js getters inconsistently create doc ref. and access properties

### ISSUE THREAD

**Issue by richardkhillah** [NamrataAcharya02/IRLAmongUs#108]
## Description
Getters in Player.js do not all consistently create a reference to the database. 

Some getter calls use the correct `this.#id` when setting the ref doc(db, 'players', this.#id), which is correct.
Some getter calls use the incorrect `this.id` when setting the ref doc(db, 'players', this.id), which is incorrect.

## Steps to Reproduce
Steps to reproduce the bug:
- [ ] create and initialize a new PlayerGameController().init();
- [ ] run the controller.joinRoom() with appropriate parameters (roomCode, name);
- [ ] get the error shown below.

## Expected Behavior
appropriately alter the player objects

## Additional Context
Enter any other details such as dependencies, environment, examples, etc.

## Relevant screenshots
<img width="484" alt="Screenshot 2023-12-03 at 19 10 49" src="https://github.com/NamrataAcharya02/IRLAmongUs/assets/25072000/d0a7bd78-3a09-44cc-88d9-804109195bc9">

**Comment by jlemoff** [comment]
fixed it on 12
