### ISSUE TITLE
[BUG] - Room.js updateNumTasksToDo calls itself 

### ISSUE THREAD

**Issue by NamrataAcharya02** [NamrataAcharya02/IRLAmongUs#99]
## Description
UpdateNumTasksToDo calls itself instead of setNum…

- [ ] fix it

## Expected Behavior
Give a clear and concise description of what should be the expected behavior.

## Additional Context
Enter any other details such as dependencies, environment, examples, etc.

## Relevant screenshots
If applicable, add screenshots to help illustrate the bug.

**Comment by richardkhillah** [comment]
issue was local to create-admin-model branch, so the issue was fixed, committed, and pushed there. i.e., resolved there.
